export type Lang = "fr" | "en";

export const copy = {
  fr: {
    nav: {
      mission: "Mission",
      how: "Fonctionnement",
      market: "Marché",
      token: "Token",
      nusd: "nUSD",
      paper: "Whitepaper",
      transparency: "Transparence",
      contact: "Contact",
      donate: "Faire un don",
      connect: "Connecter",
      disconnect: "Déconnecter",
      swap: "Swap",
      account: "Compte",
      associations: "Associations",
      space: "Espace",
      signIn: "Connexion",
      signOut: "Déconnexion",
      download: "Télécharger",
    },
    hero: {
      eyebrow: "Association loi 1901 · Solana",
      titleBefore: "Chaque don,",
      titleAccent: "visible.",
      titleAfter: "Pour toujours.",
      lead: "Nexa FLY construit l’infrastructure pour que les dons caritatifs soient traçables, publics, et accessibles partout — sans intermédiaire opaque.",
      cta: "Faire un don",
      secondary: "Lire le whitepaper",
      space: "Espace association",
      download: "Télécharger le dossier",
      proofRna: "RNA W131019858",
      proofWallet: "Wallet public",
      proofChain: "On-chain Solana",
    },
    snapshot: {
      title: "Preuve, pas de promesse",
      symbol: "Symbole",
      network: "Réseau",
      supply: "Supply",
      status: "Statut",
      statusValue: "Association déclarée",
    },
    problem: {
      tag: "Le constat",
      title: "La confiance ne se décrète pas. Elle se vérifie.",
      items: [
        {
          title: "Dons opaques",
          body: "Trop d’organisations demandent la confiance sans offrir de preuve. Les donateurs voient un reçu, pas le chemin de l’argent.",
        },
        {
          title: "Frais et frontières",
          body: "Virements, intermédiaires, délais : donner depuis l’étranger vers une association reste trop cher et trop lent.",
        },
        {
          title: "Rapports, pas de preuves",
          body: "Un PDF annuel n’est pas une traçabilité. La blockchain enregistre chaque mouvement, publiquement, en continu.",
        },
      ],
    },
    how: {
      tag: "Fonctionnement",
      title: "Trois gestes. Une piste d’audit.",
      steps: [
        {
          n: "01",
          title: "Vous donnez",
          body: "SOL, USDC ou FLY vers le wallet de transparence — ou un don en euros par contact. Pas de passage en boîte noire.",
        },
        {
          n: "02",
          title: "C’est écrit",
          body: "Chaque mouvement est enregistré sur Solana. Immutable, horodaté, consultable par n’importe qui.",
        },
        {
          n: "03",
          title: "Vous vérifiez",
          body: "Le wallet associatif est public. Ouvrez Solscan, suivez les fonds, posez des questions avec des faits.",
        },
      ],
    },
    mission: {
      tag: "Qui nous sommes",
      title: "Une association, pas un slogan.",
      body: "Nexa FLY est une association française déclarée (loi 1901), basée à Salon-de-Provence. Notre objet : promouvoir la blockchain pour garantir la transparence des dons, faciliter la collecte en crypto-monnaie, et fédérer associations, développeurs et donateurs autour d’un rail commun.",
      quote:
        "Aider les organisations à recevoir des dons de façon plus transparente, grâce à la blockchain et à des outils numériques modernes.",
    },
    market: {
      tag: "En direct",
      title: "FLY / USDC, le carnet réel.",
      lead: "Prix, volume et liquidité de la paire FLY–USDC sur Raydium — pas la paire interne nUSD.",
      price: "Prix",
      liq: "Liquidité",
      vol: "Volume 24h",
      change: "24h",
      txns: "Tx 24h",
      pair: "Paire",
      chart: "Prix et volume · FLY / USDC (1h)",
      loading: "Lecture du carnet…",
      error: "Flux marché indisponible pour le moment.",
      openDex: "Ouvrir DexScreener",
      swap: "Swap USDC → FLY",
      vol5: "5m",
      vol1h: "1h",
      vol6h: "6h",
      vol24h: "24h",
    },
    token: {
      tag: "FLY",
      title: "Le token de l’association.",
      lead: "FLY n’est pas un mème. C’est le jeton officiel d’une association enregistrée, conçu pour tracer, simplifier et relier les dons.",
      name: "Nom",
      symbol: "Symbole",
      network: "Réseau",
      contract: "Contrat",
      copy: "Copier",
      copied: "Copié",
      get: "Obtenir FLY",
      venues: [
        { key: "jupiter", label: "Jupiter", hint: "Swap" },
        { key: "titan", label: "Titan", hint: "Swap" },
        { key: "orca", label: "Orca", hint: "Swap" },
        { key: "raydium", label: "Raydium", hint: "Swap" },
        { key: "meteora", label: "Meteora", hint: "Liquidité" },
        { key: "solscanToken", label: "Solscan", hint: "Explorateur" },
        { key: "dexscreener", label: "DexScreener", hint: "Marché" },
      ],
    },
    transparency: {
      tag: "Preuve on-chain",
      title: "Le wallet de transparence.",
      lead: "Toutes les rentrées associatives destinées à être publiques passent par cette adresse. Copiez-la, ouvrez-la, auditez-la.",
      copy: "Copier l’adresse",
      view: "Voir sur Solscan",
      donateHere: "Donner vers ce wallet",
    },
    projects: {
      tag: "En cours",
      title: "Ce que nous construisons",
      items: [
        {
          title: "Plateforme de dons",
          body: "Des outils pour que les associations reçoivent des dons transparents, depuis n’importe où.",
        },
        {
          title: "Systèmes de transparence",
          body: "Reporting public et vérification blockchain des financements caritatifs.",
        },
        {
          title: "Innovation communautaire",
          body: "Collaboration entre développeurs, associations et donateurs pour des outils vraiment utiles.",
        },
      ],
    },
    team: {
      tag: "Gouvernance",
      title: "Dirigée par ses fondateurs, encadrée par la loi 1901.",
      body: "Nexa FLY est gouvernée par ses membres fondateurs et opère dans le cadre associatif français. Pas d’équipe anonyme, pas de « doxxed soon ».",
      role: "Co-fondateur",
    },
    faq: {
      tag: "Questions",
      title: "Ce qu’on nous demande.",
      items: [
        {
          q: "Nexa FLY est-elle une vraie association ?",
          a: "Oui. Association déclarée loi 1901, RNA W131019858, SIREN 101736536, siège à Salon-de-Provence. Les actes (récépissé, SIREN, JOAFE) sont en lien dans le pied de page.",
        },
        {
          q: "À quoi sert le token FLY ?",
          a: "FLY est le jeton officiel de l’association sur Solana. Il sert de rail commun pour tracer les dons, simplifier les redistributions et relier les organisations — pas d’un simple ticker de spéculation.",
        },
        {
          q: "À quoi sert le nUSD ?",
          a: "nUSD est le stable interne, adossé 1:1 à l’USDC. Il sert aux dons et aux pools. Le carnet public du site lit FLY / USDC, la paire avec le volume qui compte.",
        },
        {
          q: "Comment vérifier un don ?",
          a: "Ouvrez le wallet de transparence sur Solscan. Chaque transaction y est publique. C’est le principe : vous n’avez pas à nous croire, vous pouvez regarder.",
        },
        {
          q: "Comment donner ?",
          a: "Envoyez SOL, USDC ou FLY vers le wallet public, ou achetez FLY via le swap Jupiter intégré. Pour un don en euros ou un partenariat d’association, écrivez à contact@nexafly.org.",
        },
        {
          q: "Les associations du répertoire ont-elles déjà leur wallet ?",
          a: "Pas encore. Les dons vers ces organisations arrivent sur le wallet de transparence Nexa FLY, avec le nom inscrit au registre. Nexa redistribue ensuite. Quand une association relie son propre wallet, les dons suivants vont directement chez elle.",
        },
        {
          q: "Mon association peut-elle rejoindre ?",
          a: "Oui — c’est le cœur du projet. Créez un compte, ouvrez votre espace, connectez le wallet de réception. Les donateurs (et Nexa FLY) peuvent alors vous envoyer SOL, USDC ou FLY, avec une piste publique.",
        },
        {
          q: "Les dons ouvrent-ils droit à un reçu fiscal ?",
          a: "Cela dépend du don et du cadre. Ne présumez pas : écrivez-nous et nous indiquerons ce qui est possible, sans promesse marketing.",
        },
      ],
    },
    contact: {
      tag: "Écrire",
      title: "Partenariat, don, question.",
      lead: "Associations, développeurs, donateurs — une seule adresse.",
      name: "Nom",
      email: "Email",
      message: "Message",
      send: "Ouvrir le mail",
      placeholderName: "Votre nom",
      placeholderEmail: "vous@organisation.org",
      placeholderMessage: "Comment on peut travailler ensemble…",
    },
    donate: {
      title: "Faire un don",
      lead: "Choisissez le rail. Dans tous les cas, le wallet associatif reste public.",
      onchain: "Don on-chain",
      onchainBody: "Envoyez SOL, USDC ou FLY vers le wallet de transparence.",
      swap: "Obtenir FLY",
      swapBody: "Cours USDC → FLY ici. Le swap s’exécute sur Jupiter ou Titan.",
      euro: "Don en euros",
      euroBody: "Écrivez-nous. On vous indique le virement et le suivi.",
      partners: "Association partenaire",
      partnersBody: "Choisissez une association. Les fonds arrivent sur le wallet Nexa FLY, nommés au registre, puis redistribués.",
      close: "Fermer",
      connected: "Wallet connecté",
      noWallet: "Aucun wallet Solana détecté. Installez Phantom ou Solflare, puis reconnectez-vous.",
      install: "Installer Phantom",
    },
    nusdPage: {
      eyebrow: "Stable interne · adossé 1:1 à l’USDC",
      title: "nUSD, le dollar du rail FLY.",
      lead: "Nexa USD est le jeton stable interne de l’écosystème. Il sert aux échanges, aux dons et aux pools de liquidité, avec une parité visée 1:1 avec l’USDC.",
      backing: "Adossé 1:1 à l’USDC",
      mint: "Contrat",
      network: "Réseau",
      peg: "Parité",
      pegValue: "1 nUSD ≈ 1 USDC",
      whyTag: "Rôle",
      whyTitle: "Pourquoi un stable interne ?",
      why: "USDC reste le rail externe. nUSD est l’unité de compte à l’intérieur de Nexa FLY — dons, pools, trésorerie associative — contrôlée par l’association, vérifiable on-chain.",
      uses: [
        {
          title: "Dons",
          body: "Un donateur peut entrer en USDC puis opérer en nUSD sans exposition au prix du FLY.",
        },
        {
          title: "Liquidité",
          body: "Les pools nUSD / FLY existent. Le carnet public du site, lui, lit FLY / USDC — le marché le plus profond en volume.",
        },
        {
          title: "Trésorerie",
          body: "L’association peut loger des fonds stables tout en restant sur Solana, sous le wallet de transparence.",
        },
      ],
      explorer: "Voir sur Solscan",
      swap: "Swap USDC → nUSD",
      titan: "Swap sur Titan",
      downloadHtml: "Télécharger nusd.html",
      downloadHint: "Un seul fichier. Ensuite, double-cliquez-le : la page s’ouvre.",
      stepsTag: "Obtenir",
      stepsTitle: "Comment entrer en nUSD.",
      steps: [
        {
          k: "01",
          t: "Wallet Solana",
          b: "Phantom, Solflare, Backpack, Ledger — n’importe quel wallet compatible.",
        },
        {
          k: "02",
          t: "Swap USDC → nUSD",
          b: "Le change s’exécute sur Jupiter ou Titan, en public, sur Solana.",
        },
        {
          k: "03",
          t: "Donner ou fournir de la liquidité",
          b: "nUSD sert aux dons stables et aux pools, sans exposition au prix du FLY.",
        },
      ],
      specsTag: "Fiche",
      specsTitle: "Le contrat, en clair.",
      specs: [
        { k: "Nom", v: "Nexa USD" },
        { k: "Symbole", v: "nUSD" },
        { k: "Standard", v: "Solana SPL" },
        { k: "Parité visée", v: "1 nUSD ≈ 1 USDC" },
        { k: "Émetteur", v: "Association Nexa FLY" },
        { k: "Contrôle", v: "L’association, vérifiable on-chain" },
      ],
      faqTag: "Questions",
      faqTitle: "Ce que nUSD n’est pas.",
      faq: [
        {
          t: "nUSD n’est pas de l’USDC",
          b: "USDC reste le dollar externe (Circle). nUSD est l’unité interne de Nexa FLY, adossée 1:1, pour dons et pools.",
        },
        {
          t: "Ce n’est pas un dépôt bancaire",
          b: "Pas de garantie de rendement, pas un compte. Un jeton SPL sur Solana, sous le contrôle de l’association.",
        },
        {
          t: "Il peut évoluer",
          b: "Nexa peut étendre les usages (dons, pools, trésorerie) tout en gardant la parité visée et la transparence on-chain.",
        },
      ],
      notice:
        "nUSD est un jeton d’utilité interne. Il ne constitue ni un titre financier, ni un conseil, ni une promesse de rendement.",
      compareTag: "Trois unités",
      compareTitle: "USDC, nUSD, FLY — chacun son rôle.",
      compare: [
        {
          title: "USDC",
          body: "Le dollar externe. C’est la paire FLY / USDC que le carnet public du site lit — le volume qui compte.",
        },
        {
          title: "nUSD",
          body: "Le dollar interne, adossé 1:1. Il sert aux dons et aux pools sans exposition au prix du FLY.",
        },
        {
          title: "FLY",
          body: "Le jeton de l’association. Rail de gouvernance, de traçabilité, et de liquidité sur Solana.",
        },
      ],
    },
    paperPage: {
      eyebrow: "Document fondateur",
      title: "Whitepaper Nexa (FLY)",
      lead: "Le texte officiel de l’association : mission, utilité du token, tokenomics, feuille de route. Même lecture que le reste du site — le PDF reste téléchargeable.",
      download: "Télécharger le PDF",
      statsTag: "Tokenomics",
      stats: [
        { k: "Nom", v: "Nexa" },
        { k: "Symbole", v: "FLY" },
        { k: "Supply", v: "899 927 FLY" },
        { k: "Standard", v: "Solana SPL" },
      ],
      roadmapTag: "Feuille de route",
      roadmapTitle: "De la création du token à la plateforme.",
      roadmap: [
        {
          k: "Q2 2025",
          t: "Fondations",
          b: "Concept du projet, création du token FLY, cadre associatif.",
        },
        {
          k: "Q3 2025",
          t: "Liquidité",
          b: "Premiers pools Raydium et Orca. Le carnet public lit désormais FLY / USDC.",
        },
        {
          k: "Q4 2025",
          t: "Listings & wallets",
          b: "Listings, intégration Phantom et Solflare, présence DexScreener / GeckoTerminal.",
        },
        {
          k: "2026",
          t: "Plateforme",
          b: "Plateforme complète, certificats de don NFT, extension européenne.",
        },
      ],
      sections: [
        {
          k: "01",
          t: "Introduction",
          b: "Nexa est une association française à but non lucratif conçue pour réunir plusieurs organisations caritatives sous un même écosystème. Sa mission : faciliter les dons en crypto de façon transparente, sûre et efficace, en s’appuyant sur Solana — rapide, peu coûteuse — pour moderniser la philanthropie.",
        },
        {
          k: "02",
          t: "Vue d’ensemble",
          b: "Nexa fournit une plateforme décentralisée où les associations reçoivent des dons en cryptomonnaie sans intermédiaire. Le token FLY est le jeton d’utilité de l’écosystème : il permet de suivre les contributions en temps réel et de participer aux décisions de gouvernance.",
        },
        {
          k: "03",
          t: "Utilité du token",
          b: "Dons : FLY peut servir de contribution directe aux associations enregistrées. Gouvernance : les détenteurs votent les propositions et les partenariats. Liquidité : FLY se négocie sur les DEX Solana (Raydium, Orca). Incitations : membres et associations partenaires peuvent recevoir du FLY pour leur participation.",
        },
        {
          k: "04",
          t: "Écosystème & partenariats",
          b: "Nexa collabore avec des organisations à but non lucratif vérifiées pour que les dons atteignent des bénéficiaires légitimes. Plusieurs DEX Solana portent la liquidité. Phantom et Solflare rendent FLY accessible partout.",
        },
        {
          k: "05",
          t: "Technologie",
          b: "Blockchain : Solana. Standard : SPL Token. Audits : revues internes réalisées, audits externes prévus. Analytique : toutes les transactions sont suivies on-chain (explorateurs, DexScreener, GeckoTerminal).",
        },
        {
          k: "06",
          t: "Communauté & gouvernance",
          b: "La communauté est au centre. Les détenteurs de FLY peuvent voter, proposer des partenariats et influer sur la croissance. Contributions et votes sont publics on-chain.",
        },
      ],
    },
    wallet: {
      tag: "Compte Solana",
      title: "Connecter un wallet",
      lead: "Phantom, Solflare, Backpack, Ledger, mobile — n’importe quel wallet Solana. Une fois connecté, votre adresse devient votre compte.",
      connect: "Connecter le wallet",
      disconnect: "Déconnecter",
      none: "Aucun wallet d’extension détecté. Installez-en un, ou ouvrez le swap Jupiter / Titan pour les wallets mobile.",
      detected: "Détecté — cliquer pour connecter",
      install: "Installer",
      any: "Wallets Solana",
      more: "Autres wallets",
      mobile: "Tous les wallets, y compris mobile",
      mobileBody: "Jupiter ou Titan : Phantom, Solflare, Backpack, Ledger et WalletConnect.",
      account: "Compte",
      session: "Compte lié à ce wallet",
      copyAddress: "Copier l’adresse",
      explorer: "Voir sur Solscan",
      buyFly: "Acheter FLY",
    },
    swap: {
      tag: "Swap",
      title: "Acheter FLY, ici.",
      lead: "Cours en direct. USDC ou SOL vers FLY. Le swap s’exécute sur Jupiter ou Titan — sans widget qui bloque la page.",
      loading: "Cours…",
      error: "Cours indisponible pour le moment.",
      open: "Swap sur Jupiter",
      titan: "Swap sur Titan",
      powered: "Routage Jupiter · Titan",
      pay: "Vous payez",
      receive: "Vous recevez",
      rate: "Cours",
    },
    org: {
      tag: "Réseau",
      title: "Les associations du rail.",
      lead: "Le répertoire s’ouvre. Les dons vers ces organisations transiteront par le wallet de transparence Nexa FLY — Nexa redistribue ensuite, nom par nom — jusqu’à ce que chaque association relie le sien.",
      create: "Créer un espace",
      openSpace: "Ouvrir mon espace",
      all: "Toutes les associations",
      empty: "Le réseau s’ouvre.",
      emptyLead: "Le répertoire se remplit. Les associations partenaires peuvent aussi ouvrir leur propre espace.",
      featured: "Réseau",
      hosted: "Via Nexa FLY",
      hostedLead:
        "Les fonds arrivent sur le wallet de transparence Nexa FLY. Nexa redistribue ensuite à cette organisation, d’après le registre — jusqu’à ce qu’elle relie son propre wallet.",
      hostedNote: "En attendant qu’ils viennent lier leur adresse.",
      france: "France",
      world: "Monde",
      filterAll: "Toutes",
      filterEmpty: "Aucune association dans ce filtre.",
      gifts: "dons enregistrés",
      gift: "don",
      wallet: "Wallet de réception",
      noWallet: "Wallet pas encore lié",
      noWalletBody: "Cette association n’a pas encore publié d’adresse de réception.",
      donate: "Faire un don",
      donateLead: "Envoyez SOL, USDC, FLY ou nUSD vers le wallet indiqué, puis inscrivez le don au registre — avec le nom de l’association.",
      onchain: "Adresse on-chain",
      record: "Enregistrer le don",
      recorded: "Don inscrit au registre.",
      recordLead: "Le transfert se fait dans votre wallet. Ici, on écrit la trace pour l’association et ses donateurs.",
      token: "Jeton",
      amount: "Montant",
      donorName: "Votre nom (optionnel)",
      donorNamePh: "Anonyme si vide",
      message: "Message (optionnel)",
      messagePh: "Une ligne pour l’association…",
      tx: "Signature de transaction (optionnel)",
      txPh: "Collez la signature Solana",
      send: "Inscrire au registre",
      anonymous: "Anonyme",
      fromNexa: "Redistribution Nexa FLY",
      fromDonor: "Donateur",
      copyWallet: "Copier l’adresse",
      viewChain: "Voir sur Solscan",
      city: "Ville",
      category: "Catégorie",
      website: "Site",
      rna: "RNA",
      since: "Depuis",
      holdings: "Soldes publics",
      connectWallet: "Connecter le wallet de réception",
      useWallet: "Utiliser ce wallet",
      walletSaved: "Wallet lié à l’espace.",
      profile: "Profil public",
      save: "Enregistrer l’espace",
      saved: "Espace mis à jour.",
      publicPage: "Page publique",
      onboardTitle: "Ouvrir l’espace de votre association.",
      onboardLead: "Un nom, une ville, un wallet. Les donateurs vous trouvent ensuite dans le répertoire.",
      name: "Nom de l’association",
      namePh: "Les Colibris de Provence",
      tagline: "Phrase d’accroche",
      taglinePh: "Ce que vous faites, en une ligne.",
      description: "Présentation",
      descriptionPh: "Mission, actions, comment les dons sont utilisés…",
      slug: "Adresse de la page",
      cityPh: "Salon-de-Provence",
      websitePh: "https://…",
      rnaPh: "W1310…",
      published: "Espace visible dans le répertoire",
      dashTitle: "Votre espace",
      dashLead: "Profil, wallet de réception, dons reçus — de Nexa FLY et des donateurs.",
      receive: "Réception",
      receiveLead: "Connectez le wallet qui recevra les dons. Il devient public sur votre page.",
      ledger: "Registre des dons",
      ledgerEmpty: "Aucun don enregistré pour le moment. Partagez votre page.",
      nexaGrant: "De Nexa FLY",
      preview: "Aperçu",
      needWallet: "Liez d’abord un wallet pour recevoir.",
      errName: "Le nom est trop court.",
      errSlug: "Cette adresse de page n’est pas disponible.",
      errWallet: "Adresse Solana invalide.",
      errWalletTaken: "Ce wallet est déjà lié à un autre espace.",
      errAmount: "Indiquez un montant.",
      errGeneric: "Impossible d’enregistrer. Réessayez.",
      categories: {
        solidarity: "Solidarité",
        education: "Éducation",
        health: "Santé",
        environment: "Environnement",
        culture: "Culture",
        animal: "Animal",
        local: "Local",
        other: "Autre",
      },
    },
    login: {
      tag: "Espace association",
      title: "Connectez l’espace de votre organisation.",
      lead: "Un compte pour publier votre page, lier un wallet Solana, et recevoir des dons de Nexa FLY ou de n’importe qui.",
      google: "Continuer avec Google",
      x: "Continuer avec X",
      or: "ou par email",
      email: "Email",
      password: "Mot de passe",
      name: "Nom",
      namePh: "Votre association ou votre nom",
      signIn: "Se connecter",
      signUp: "Créer le compte",
      switchIn: "Déjà un compte ? Connexion",
      switchUp: "Pas encore d’espace ? Créer un compte",
      error: "Connexion impossible. Vérifiez vos identifiants.",
      submitting: "Un instant…",
      hint: "Le compte ouvre l’espace association. Les donateurs, eux, n’ont pas besoin de s’inscrire.",
      back: "Retour au site",
    },
    footer: {
      blurb:
        "Association loi 1901. Dons transparents, on-chain, pour les organisations et leurs donateurs.",
      legal: "Mentions",
      docs: "Documents",
      social: "Réseaux",
      copyright: "© Nexa FLY Association",
      download: "Télécharger le site",
    },
    pack: {
      tag: "Publier",
      title: "Télécharger le dossier du site.",
      lead: "Un zip prêt pour Cloudflare : index.html, pages, logos, whitepaper. Pas de TypeScript.",
      button: "Télécharger nexa-static.zip",
    },
  },
  en: {
    nav: {
      mission: "Mission",
      how: "How it works",
      market: "Market",
      token: "Token",
      nusd: "nUSD",
      paper: "Whitepaper",
      transparency: "Transparency",
      contact: "Contact",
      donate: "Donate",
      connect: "Connect",
      disconnect: "Disconnect",
      swap: "Swap",
      account: "Account",
      associations: "Associations",
      space: "Space",
      signIn: "Sign in",
      signOut: "Sign out",
      download: "Download",
    },
    hero: {
      eyebrow: "French Law 1901 nonprofit · Solana",
      titleBefore: "Every donation,",
      titleAccent: "visible.",
      titleAfter: "Forever.",
      lead: "Nexa FLY builds the infrastructure that makes charitable giving traceable, public, and reachable from anywhere — without opaque middlemen.",
      cta: "Donate",
      secondary: "Read the whitepaper",
      space: "Association space",
      download: "Download the folder",
      proofRna: "RNA W131019858",
      proofWallet: "Public wallet",
      proofChain: "On-chain Solana",
    },
    snapshot: {
      title: "Proof, not a pitch deck",
      symbol: "Symbol",
      network: "Network",
      supply: "Supply",
      status: "Status",
      statusValue: "Registered nonprofit",
    },
    problem: {
      tag: "The problem",
      title: "Trust is not a tagline. It is a ledger.",
      items: [
        {
          title: "Opaque giving",
          body: "Too many organisations ask for trust without offering proof. Donors get a receipt, not a path.",
        },
        {
          title: "Fees and borders",
          body: "Wires, intermediaries, delays: sending money to a charity from abroad is still too slow and too expensive.",
        },
        {
          title: "Reports, not evidence",
          body: "A yearly PDF is not traceability. The chain records every movement, in public, continuously.",
        },
      ],
    },
    how: {
      tag: "How it works",
      title: "Three moves. One audit trail.",
      steps: [
        {
          n: "01",
          title: "You give",
          body: "SOL, USDC or FLY to the transparency wallet — or euros by email. No black box in between.",
        },
        {
          n: "02",
          title: "It is written",
          body: "Every movement is recorded on Solana. Immutable, timestamped, readable by anyone.",
        },
        {
          n: "03",
          title: "You verify",
          body: "The association wallet is public. Open Solscan, follow the funds, ask questions with facts.",
        },
      ],
    },
    mission: {
      tag: "Who we are",
      title: "An association, not a slogan.",
      body: "Nexa FLY is a registered French nonprofit (Law 1901) based in Salon-de-Provence. Our purpose: use blockchain to guarantee donation transparency, make crypto giving practical, and connect charities, developers and donors on a shared rail.",
      quote:
        "Help organisations receive donations more transparently, using blockchain and modern digital tools.",
    },
    market: {
      tag: "Live",
      title: "FLY / USDC, the real book.",
      lead: "Price, volume and liquidity from the FLY–USDC Raydium pair — not the internal nUSD pair.",
      price: "Price",
      liq: "Liquidity",
      vol: "24h volume",
      change: "24h",
      txns: "24h txns",
      pair: "Pair",
      chart: "Price & volume · FLY / USDC (1h)",
      loading: "Reading the book…",
      error: "Market feed unavailable right now.",
      openDex: "Open DexScreener",
      swap: "Swap USDC → FLY",
      vol5: "5m",
      vol1h: "1h",
      vol6h: "6h",
      vol24h: "24h",
    },
    token: {
      tag: "FLY",
      title: "The association’s token.",
      lead: "FLY is not a meme. It is the official token of a registered nonprofit, built to trace, simplify and connect donations.",
      name: "Name",
      symbol: "Symbol",
      network: "Network",
      contract: "Contract",
      copy: "Copy",
      copied: "Copied",
      get: "Get FLY",
      venues: [
        { key: "jupiter", label: "Jupiter", hint: "Swap" },
        { key: "titan", label: "Titan", hint: "Swap" },
        { key: "orca", label: "Orca", hint: "Swap" },
        { key: "raydium", label: "Raydium", hint: "Swap" },
        { key: "meteora", label: "Meteora", hint: "Liquidity" },
        { key: "solscanToken", label: "Solscan", hint: "Explorer" },
        { key: "dexscreener", label: "DexScreener", hint: "Market" },
      ],
    },
    transparency: {
      tag: "On-chain proof",
      title: "The transparency wallet.",
      lead: "Public association inflows go through this address. Copy it, open it, audit it.",
      copy: "Copy address",
      view: "View on Solscan",
      donateHere: "Donate to this wallet",
    },
    projects: {
      tag: "In progress",
      title: "What we are building",
      items: [
        {
          title: "Donation platform",
          body: "Tools that let associations receive transparent donations from anywhere.",
        },
        {
          title: "Transparency systems",
          body: "Public reporting and blockchain verification for charitable funding.",
        },
        {
          title: "Community innovation",
          body: "Collaboration between developers, nonprofits and donors on tools that actually get used.",
        },
      ],
    },
    team: {
      tag: "Governance",
      title: "Founder-led, Law 1901 framed.",
      body: "Nexa FLY is governed by its founding members inside the French nonprofit framework. No anonymous team. No “doxxed soon”.",
      role: "Co-founder",
    },
    faq: {
      tag: "Questions",
      title: "What people ask.",
      items: [
        {
          q: "Is Nexa FLY a real association?",
          a: "Yes. Registered French Law 1901 nonprofit, RNA W131019858, SIREN 101736536, based in Salon-de-Provence. Registration, SIREN and JOAFE documents are linked in the footer.",
        },
        {
          q: "What is the FLY token for?",
          a: "FLY is the association’s official token on Solana. It is a shared rail to trace donations, simplify distribution and connect organisations — not a ticker with a story taped on.",
        },
        {
          q: "What is nUSD?",
          a: "nUSD is the internal stable, backed 1:1 with USDC, used for gifts and pools. The public book on this site reads FLY / USDC — the pair with the volume that matters.",
        },
        {
          q: "How do I verify a donation?",
          a: "Open the transparency wallet on Solscan. Every transaction is public. You do not have to trust us. You can look.",
        },
        {
          q: "How do I donate?",
          a: "Send SOL, USDC or FLY to the public wallet, or buy FLY via the Jupiter swap on this site. For euro donations or an association partnership, write to contact@nexafly.org.",
        },
        {
          q: "Do listed associations already have their own wallet?",
          a: "Not yet. Gifts to these organisations land on the Nexa FLY transparency wallet, named on the ledger. Nexa then redistributes. When an association links its own wallet, later gifts go to them directly.",
        },
        {
          q: "Can my association join?",
          a: "Yes — that is the point. Create an account, open your space, connect the receiving wallet. Donors (and Nexa FLY) can then send you SOL, USDC or FLY, with a public trail.",
        },
        {
          q: "Do donations come with a tax receipt?",
          a: "It depends on the gift and the legal frame. Do not assume: write to us and we will say what is possible, without a marketing promise.",
        },
      ],
    },
    contact: {
      tag: "Write",
      title: "Partnership, gift, question.",
      lead: "Associations, developers, donors — one address.",
      name: "Name",
      email: "Email",
      message: "Message",
      send: "Open email",
      placeholderName: "Your name",
      placeholderEmail: "you@organisation.org",
      placeholderMessage: "How we might work together…",
    },
    donate: {
      title: "Donate",
      lead: "Pick a rail. The association wallet stays public either way.",
      onchain: "On-chain gift",
      onchainBody: "Send SOL, USDC or FLY to the transparency wallet.",
      swap: "Get FLY",
      swapBody: "USDC → FLY quote here. Execute the swap on Jupiter or Titan.",
      euro: "Euro gift",
      euroBody: "Write to us. We will share the transfer details and the trail.",
      partners: "Partner association",
      partnersBody: "Pick an association. Funds land on the Nexa FLY wallet, named on the ledger, then redistributed.",
      close: "Close",
      connected: "Wallet connected",
      noWallet: "No Solana wallet detected. Install Phantom or Solflare, then come back.",
      install: "Install Phantom",
    },
    nusdPage: {
      eyebrow: "Internal stable · 1:1 USDC",
      title: "nUSD, the dollar on the FLY rail.",
      lead: "Nexa USD is the ecosystem’s internal stable token. It is built for swaps, donations and liquidity pools, with a 1:1 target against USDC.",
      backing: "Backed 1:1 with USDC",
      mint: "Contract",
      network: "Network",
      peg: "Peg",
      pegValue: "1 nUSD ≈ 1 USDC",
      whyTag: "Role",
      whyTitle: "Why an internal stable?",
      why: "USDC stays the external rail. nUSD is the unit of account inside Nexa FLY — gifts, pools, association treasury — controlled by the nonprofit, verifiable on-chain.",
      uses: [
        {
          title: "Donations",
          body: "A donor can enter in USDC, then operate in nUSD without taking FLY price risk.",
        },
        {
          title: "Liquidity",
          body: "nUSD / FLY pools exist. The public book on this site reads FLY / USDC — the pair with the meaningful volume.",
        },
        {
          title: "Treasury",
          body: "The association can hold stable funds on Solana, still under the transparency wallet.",
        },
      ],
      explorer: "View on Solscan",
      swap: "Swap USDC → nUSD",
      titan: "Swap on Titan",
      downloadHtml: "Download nusd.html",
      downloadHint: "One file. Then double-click it: the page opens.",
      stepsTag: "Get nUSD",
      stepsTitle: "How to enter in nUSD.",
      steps: [
        {
          k: "01",
          t: "Solana wallet",
          b: "Phantom, Solflare, Backpack, Ledger — any compatible wallet.",
        },
        {
          k: "02",
          t: "Swap USDC → nUSD",
          b: "The swap runs on Jupiter or Titan, in public, on Solana.",
        },
        {
          k: "03",
          t: "Give or provide liquidity",
          b: "nUSD is for stable gifts and pools, without FLY price exposure.",
        },
      ],
      specsTag: "Sheet",
      specsTitle: "The contract, plainly.",
      specs: [
        { k: "Name", v: "Nexa USD" },
        { k: "Symbol", v: "nUSD" },
        { k: "Standard", v: "Solana SPL" },
        { k: "Target peg", v: "1 nUSD ≈ 1 USDC" },
        { k: "Issuer", v: "Nexa FLY association" },
        { k: "Control", v: "The association, verifiable on-chain" },
      ],
      faqTag: "Questions",
      faqTitle: "What nUSD is not.",
      faq: [
        {
          t: "nUSD is not USDC",
          b: "USDC stays the external dollar (Circle). nUSD is Nexa FLY’s internal unit, backed 1:1, for gifts and pools.",
        },
        {
          t: "Not a bank deposit",
          b: "No yield promise, not an account. An SPL token on Solana, under the association’s control.",
        },
        {
          t: "It can evolve",
          b: "Nexa can extend uses (gifts, pools, treasury) while keeping the target peg and on-chain transparency.",
        },
      ],
      notice:
        "nUSD is an internal utility token. It is not a security, investment advice, or a return guarantee.",
      compareTag: "Three units",
      compareTitle: "USDC, nUSD, FLY — each has a job.",
      compare: [
        {
          title: "USDC",
          body: "The external dollar. The public book on this site reads FLY / USDC — the volume that matters.",
        },
        {
          title: "nUSD",
          body: "The internal dollar, backed 1:1. Used for gifts and pools without taking FLY price risk.",
        },
        {
          title: "FLY",
          body: "The association token. Governance, traceability, and liquidity on Solana.",
        },
      ],
    },
    paperPage: {
      eyebrow: "Founding document",
      title: "Nexa (FLY) whitepaper",
      lead: "The association’s official text: mission, token utility, tokenomics, roadmap. Same reading as the rest of the site — the PDF remains downloadable.",
      download: "Download PDF",
      statsTag: "Tokenomics",
      stats: [
        { k: "Name", v: "Nexa" },
        { k: "Symbol", v: "FLY" },
        { k: "Supply", v: "899,927 FLY" },
        { k: "Standard", v: "Solana SPL" },
      ],
      roadmapTag: "Roadmap",
      roadmapTitle: "From token creation to the platform.",
      roadmap: [
        {
          k: "Q2 2025",
          t: "Foundations",
          b: "Project concept, FLY token creation, nonprofit frame.",
        },
        {
          k: "Q3 2025",
          t: "Liquidity",
          b: "First Raydium and Orca pools. The public book now reads FLY / USDC.",
        },
        {
          k: "Q4 2025",
          t: "Listings & wallets",
          b: "Listings, Phantom and Solflare, DexScreener / GeckoTerminal presence.",
        },
        {
          k: "2026",
          t: "Platform",
          b: "Full platform, NFT donation certificates, European expansion.",
        },
      ],
      sections: [
        {
          k: "01",
          t: "Introduction",
          b: "Nexa is a French non-profit designed to unite charitable organisations under one ecosystem. Its mission is to make crypto donations transparent, secure and efficient, using Solana’s speed and low fees to modernise philanthropy.",
        },
        {
          k: "02",
          t: "Project overview",
          b: "Nexa provides a decentralised platform where associations receive cryptocurrency donations without intermediaries. The FLY token is the ecosystem utility token: donors can track contributions in real time and take part in governance.",
        },
        {
          k: "03",
          t: "Token utility",
          b: "Donations: FLY can be used for direct contributions to registered associations. Governance: holders vote on proposals and partnerships. Liquidity: FLY trades on Solana DEXs such as Raydium and Orca. Incentives: community members and partner associations may receive FLY for participation.",
        },
        {
          k: "04",
          t: "Ecosystem & partnerships",
          b: "Nexa works with verified non-profits so donations reach legitimate beneficiaries. Multiple Solana DEXs carry liquidity. Phantom and Solflare make FLY reachable worldwide.",
        },
        {
          k: "05",
          t: "Technology",
          b: "Blockchain: Solana. Standard: SPL Token. Audits: internal reviews done, external audits planned. Analytics: every transaction is trackable on-chain via explorers, DexScreener and GeckoTerminal.",
        },
        {
          k: "06",
          t: "Community & governance",
          b: "The community sits at the centre. FLY holders can vote, propose partnerships and shape growth. Contributions and votes are public on-chain.",
        },
      ],
    },
    wallet: {
      tag: "Solana account",
      title: "Connect a wallet",
      lead: "Phantom, Solflare, Backpack, Ledger, mobile — any Solana wallet. Once connected, your address is your account.",
      connect: "Connect wallet",
      disconnect: "Disconnect",
      none: "No browser wallet detected. Install one, or open the Jupiter / Titan swap for mobile wallets.",
      detected: "Detected — click to connect",
      install: "Install",
      any: "Solana wallets",
      more: "Other wallets",
      mobile: "Any wallet, including mobile",
      mobileBody: "Jupiter or Titan: Phantom, Solflare, Backpack, Ledger and WalletConnect.",
      account: "Account",
      session: "Account tied to this wallet",
      copyAddress: "Copy address",
      explorer: "View on Solscan",
      buyFly: "Buy FLY",
    },
    swap: {
      tag: "Swap",
      title: "Buy FLY, here.",
      lead: "Live quote. USDC or SOL to FLY. Execute on Jupiter or Titan — no widget that freezes the page.",
      loading: "Quote…",
      error: "Quote unavailable right now.",
      open: "Swap on Jupiter",
      titan: "Swap on Titan",
      powered: "Routed by Jupiter · Titan",
      pay: "You pay",
      receive: "You receive",
      rate: "Rate",
    },
    org: {
      tag: "Network",
      title: "Associations on the rail.",
      lead: "The directory is open. Gifts to these organisations go through the Nexa FLY transparency wallet — Nexa redistributes, name by name — until each association links its own.",
      create: "Create a space",
      openSpace: "Open my space",
      all: "All associations",
      empty: "The network is opening.",
      emptyLead: "The directory is filling up. Partner associations can also open their own space.",
      featured: "Network",
      hosted: "Via Nexa FLY",
      hostedLead:
        "Funds land on the Nexa FLY transparency wallet. Nexa then redistributes to this organisation from the ledger — until they link their own wallet.",
      hostedNote: "Until they come and link their address.",
      france: "France",
      world: "World",
      filterAll: "All",
      filterEmpty: "No associations in this filter.",
      gifts: "recorded gifts",
      gift: "gift",
      wallet: "Receiving wallet",
      noWallet: "No wallet linked yet",
      noWalletBody: "This association has not published a receiving address yet.",
      donate: "Donate",
      donateLead: "Send SOL, USDC, FLY or nUSD to the wallet shown, then write the gift to the ledger — with the association’s name.",
      onchain: "On-chain address",
      record: "Record the gift",
      recorded: "Gift written to the ledger.",
      recordLead: "The transfer happens in your wallet. Here we write the trail for the association and its donors.",
      token: "Token",
      amount: "Amount",
      donorName: "Your name (optional)",
      donorNamePh: "Anonymous if empty",
      message: "Message (optional)",
      messagePh: "A line for the association…",
      tx: "Transaction signature (optional)",
      txPh: "Paste the Solana signature",
      send: "Write to the ledger",
      anonymous: "Anonymous",
      fromNexa: "Nexa FLY redistribution",
      fromDonor: "Donor",
      copyWallet: "Copy address",
      viewChain: "View on Solscan",
      city: "City",
      category: "Category",
      website: "Website",
      rna: "RNA",
      since: "Since",
      holdings: "Public balances",
      connectWallet: "Connect the receiving wallet",
      useWallet: "Use this wallet",
      walletSaved: "Wallet linked to the space.",
      profile: "Public profile",
      save: "Save space",
      saved: "Space updated.",
      publicPage: "Public page",
      onboardTitle: "Open your association’s space.",
      onboardLead: "A name, a city, a wallet. Donors then find you in the directory.",
      name: "Association name",
      namePh: "Les Colibris de Provence",
      tagline: "Tagline",
      taglinePh: "What you do, in one line.",
      description: "About",
      descriptionPh: "Mission, work, how gifts are used…",
      slug: "Page address",
      cityPh: "Salon-de-Provence",
      websitePh: "https://…",
      rnaPh: "W1310…",
      published: "Visible in the directory",
      dashTitle: "Your space",
      dashLead: "Profile, receiving wallet, gifts received — from Nexa FLY and from donors.",
      receive: "Receiving",
      receiveLead: "Connect the wallet that will receive gifts. It becomes public on your page.",
      ledger: "Gift ledger",
      ledgerEmpty: "No gifts recorded yet. Share your page.",
      nexaGrant: "From Nexa FLY",
      preview: "Preview",
      needWallet: "Link a wallet first to receive.",
      errName: "The name is too short.",
      errSlug: "That page address is not available.",
      errWallet: "Invalid Solana address.",
      errWalletTaken: "That wallet is already linked to another space.",
      errAmount: "Enter an amount.",
      errGeneric: "Could not save. Try again.",
      categories: {
        solidarity: "Solidarity",
        education: "Education",
        health: "Health",
        environment: "Environment",
        culture: "Culture",
        animal: "Animals",
        local: "Local",
        other: "Other",
      },
    },
    login: {
      tag: "Association space",
      title: "Sign in to your organisation’s space.",
      lead: "One account to publish your page, link a Solana wallet, and receive gifts from Nexa FLY or anyone else.",
      google: "Continue with Google",
      x: "Continue with X",
      or: "or with email",
      email: "Email",
      password: "Password",
      name: "Name",
      namePh: "Your association or your name",
      signIn: "Sign in",
      signUp: "Create account",
      switchIn: "Already have an account? Sign in",
      switchUp: "No space yet? Create an account",
      error: "Could not sign in. Check your details.",
      submitting: "One moment…",
      hint: "The account opens the association space. Donors do not need to sign up.",
      back: "Back to the site",
    },
    footer: {
      blurb:
        "Law 1901 association. Transparent, on-chain donations for organisations and the people who fund them.",
      legal: "Legal",
      docs: "Documents",
      social: "Social",
      copyright: "© Nexa FLY Association",
      download: "Download the site",
    },
    pack: {
      tag: "Publish",
      title: "Download the site folder.",
      lead: "A zip ready for Cloudflare: index.html, pages, logos, whitepaper. No TypeScript.",
      button: "Download nexa-static.zip",
    },
  },
} as const;
