[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  VITE_AUTH_ENABLED = "true"

[functions]
  node_bundler = "none"
  included_files = ["**"]

[[headers]]
  for = "/orgs/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.mp4"
  [headers.values]
    Cache-Control = "public, max-age=604800"
