/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EspaceRouteImport } from './routes/espace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NusdRouteImport } from './routes/nusd'
import { Route as WhitepaperRouteImport } from './routes/whitepaper'
import { Route as AssociationsIndexRouteImport } from './routes/associations/index'
import { Route as AssociationsSlugRouteImport } from './routes/associations/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceRoute = EspaceRouteImport.update({
  id: '/espace',
  path: '/espace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NusdRoute = NusdRouteImport.update({
  id: '/nusd',
  path: '/nusd',
  getParentRoute: () => rootRouteImport,
} as any)
const WhitepaperRoute = WhitepaperRouteImport.update({
  id: '/whitepaper',
  path: '/whitepaper',
  getParentRoute: () => rootRouteImport,
} as any)
const AssociationsIndexRoute = AssociationsIndexRouteImport.update({
  id: '/associations/',
  path: '/associations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssociationsSlugRoute = AssociationsSlugRouteImport.update({
  id: '/associations/$slug',
  path: '/associations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/espace': typeof EspaceRoute
  '/login': typeof LoginRoute
  '/nusd': typeof NusdRoute
  '/whitepaper': typeof WhitepaperRoute
  '/associations/$slug': typeof AssociationsSlugRoute
  '/associations/': typeof AssociationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/espace': typeof EspaceRoute
  '/login': typeof LoginRoute
  '/nusd': typeof NusdRoute
  '/whitepaper': typeof WhitepaperRoute
  '/associations/$slug': typeof AssociationsSlugRoute
  '/associations': typeof AssociationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/espace': typeof EspaceRoute
  '/login': typeof LoginRoute
  '/nusd': typeof NusdRoute
  '/whitepaper': typeof WhitepaperRoute
  '/associations/$slug': typeof AssociationsSlugRoute
  '/associations/': typeof AssociationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/espace'
    | '/login'
    | '/nusd'
    | '/whitepaper'
    | '/associations/$slug'
    | '/associations/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/espace'
    | '/login'
    | '/nusd'
    | '/whitepaper'
    | '/associations/$slug'
    | '/associations'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/espace'
    | '/login'
    | '/nusd'
    | '/whitepaper'
    | '/associations/$slug'
    | '/associations/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EspaceRoute: typeof EspaceRoute
  LoginRoute: typeof LoginRoute
  NusdRoute: typeof NusdRoute
  WhitepaperRoute: typeof WhitepaperRoute
  AssociationsSlugRoute: typeof AssociationsSlugRoute
  AssociationsIndexRoute: typeof AssociationsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace': {
      id: '/espace'
      path: '/espace'
      fullPath: '/espace'
      preLoaderRoute: typeof EspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nusd': {
      id: '/nusd'
      path: '/nusd'
      fullPath: '/nusd'
      preLoaderRoute: typeof NusdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whitepaper': {
      id: '/whitepaper'
      path: '/whitepaper'
      fullPath: '/whitepaper'
      preLoaderRoute: typeof WhitepaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/associations/': {
      id: '/associations/'
      path: '/associations'
      fullPath: '/associations/'
      preLoaderRoute: typeof AssociationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/associations/$slug': {
      id: '/associations/$slug'
      path: '/associations/$slug'
      fullPath: '/associations/$slug'
      preLoaderRoute: typeof AssociationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EspaceRoute: EspaceRoute,
  LoginRoute: LoginRoute,
  NusdRoute: NusdRoute,
  WhitepaperRoute: WhitepaperRoute,
  AssociationsSlugRoute: AssociationsSlugRoute,
  AssociationsIndexRoute: AssociationsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
